# Generated by Django 4.0.4 on 2022-05-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/foods/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/halls/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/menu/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/services/%Y/%m'),
        ),
    ]
