# Generated by Django 4.0.4 on 2022-05-10 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_alter_food_image_alter_hall_image_alter_menu_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.customer')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wedding.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
