# Generated by Django 4.0.4 on 2022-05-10 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_comment_delete_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creator',
            new_name='customer',
        ),
    ]
